### ISSUE TITLE
Issue posting with account

### ISSUE THREAD

**Issue by gempir** [j3lte/pastebin-js#11]
I'm having with issues with posting pastebins as a user.

My pastes always show up as "A GUEST"

I tried this format 

```
var PastebinAPI = require('pastebin-js'),
    pastebin = new PastebinAPI({
      'api_dev_key' : 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
      'api_user_name' : 'PastebinUserName',
      'api_user_password' : 'PastebinPassword'
    });
```

or only the dev key but it doesn't seem to work. Options like expiration or listed unlisted work fine.

this is how I create a paste

`pastebin.createPaste(longStringhere, pastebin title asdf,null,0, '10M')`

**Comment by j3lte** [comment]
Confirmed. Good one. This is something that I did not anticipate. If you create a paste as public, it will never ask for the userkey (something that is needed to create a public paste on your name).

For now we handle the following configurations for privacy:

``0=public 1=unlisted 2=private``

This is direct from the [API from Pastebin](http://pastebin.com/api#7)

I have already created a fix for this (currently testing), we'll add our own privacy key:

* 0 = public, anonymous
* 1 = unlisted
* 2 = private
* 3 = public, as a user
