### ISSUE TITLE
Possilble edit?

### ISSUE THREAD

**Issue by DamnMerc** [j3lte/pastebin-js#15]
better-pastebin had the option to edit, but it's since long outdated and doesn't function correctly anymore.

**Comment by j3lte** [comment]
I'm afraid not. `better-pastebin` uses the web interface, basically mimicking a browser. `pastebin-js` uses the official REST api for Pastebin, which doesn't have an option to edit your pastes...

**Comment by DamnMerc** [comment]
Oh, alright. Would be nice if they added an edit option on their api..
