### ISSUE TITLE
 pastebin.getPaste(key) is blocked by CORS policy - how is this supposed to work

### ISSUE THREAD

**Issue by StructureOfEverything** [j3lte/pastebin-js#19]
Hi,
the code below shows my attempt to fetch a raw paste from pastebin. Unfortunately i got CORS blocked - i was expecting it. So my question is how is this supposed to work?

`
let pastebin = new PastebinAPI({
    api_dev_key: configApi.client.pastebin.api_dev_key,
    api_user_name: configApi.client.pastebin.api_user_name,
    api_user_password: configApi.client.pastebin.api_user_password,
});

var {
    key
} = request;

pastebin
    .getPaste(key)
    .then(function (data) {
        // data contains the raw paste
        console.log(data);
    })
    .fail(function (err) {
        // Something went wrong
        console.log(err);
    });
`

Access to fetch at 'https://pastebin.com/raw.php?i=XXXXXXXXXX' from origin 'http://localhost:3001' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

**Comment by j3lte** [comment]
Are you trying to do this from a browser? Pastebin-js is only working from Node.JS

**Comment by StructureOfEverything** [comment]
Its part of a react component.
But i can try it as a part of an nodejs express server. I think this will result in the same, because the orign will be localhost, too. At least on localdev.

**Comment by j3lte** [comment]
Well no... If you would do a request at your local express server, which would relay the request to pastebin, this would work. Node.JS ignores CORS, your browser doesn't

**Comment by StructureOfEverything** [comment]
Ok makes sense. Thx.
