### ISSUE TITLE
"Cannot read property "length" of undefined" - every time a post is attempted

### ISSUE THREAD

**Issue by FiftiOnGithub** [j3lte/pastebin-js#23]
Each time I try to create a post using a working key, I get this error:
[https://gyazo.com/bc56f551b0d1d203d2b93ae9b033d54e](https://gyazo.com/bc56f551b0d1d203d2b93ae9b033d54e)

Any fixes?
I'm using the exact same code as the example but with a different key obviously.

**Comment by MrAmericanMike** [comment]
I was going to report the same. I think it only happens when the pastebin couldn't be created.

It was using some 0.6.0 version, I now updated to 1.0.2

I think by reading at the code the lone that triggered this error, this may be fixed now.
