### ISSUE TITLE
How can I get a private paste?

### ISSUE THREAD

**Issue by BSDxxxx** [j3lte/pastebin-js#25]
`var PastebinAPI = require('pastebin-js'),
  pastebin = new PastebinAPI({
    'api_dev_key': 'I got it right',
    'api_user_name': 'I got it right',
    'api_user_password': 'I got it right'
  });
pastebin.listUserPastes(1)
  .then(function (data) {
    pastebin.getPaste(data[0].paste_key)
      .then(function (data) {
        console.log(data);
      })
  })
  .fail(function (err) {
    // Something went wrong
    console.log(err);
  })
`
console：Error, this is a private paste. If this is your private paste, please login to Pastebin first.

**Comment by BSDxxxx** [comment]
Sorry about the code preview, I don't know how to fix it.

**Comment by JelteMX** [comment]
(Posting from my other account)

Weird. No other issues? I'll see if I have the time to test this in the coming days. Maybe they made some changes in the API. Are you able to create private pastes from pastebin-js?

**Comment by BSDxxxx** [comment]
@JelteMX Yes, I can use it to create private pastes, also get other kinds of pastes except for private pastes.

**Comment by JelteMX** [comment]
Ok, thanks. I'll see if I can reproduce this issue soon

**Comment by j3lte** [comment]
Fixed in ``1.0.4``. You can now set ``isPrivate`` to true and you will be able to get a private paste. Syntax: ``pastebin.getPaste(pasteID, true)``.

Stupid I didn't think of this before. All this time nobody has ever asked for retrieving private pastes...

**Comment by BSDxxxx** [comment]
@JelteMX Thanks for your effort, it works great now.
