### ISSUE TITLE
Error when calling getPaste() on version 1.0.4

### ISSUE THREAD

**Issue by asromain** [j3lte/pastebin-js#29]
Hi and thanks for the good work!

I've noticed a little issue when upgrading from version 1.0.2 to 1.0.4, on the getPaste() method.

**Comment by JelteMX** [comment]
Replying from my other account...
Can you tell me the circumstances? I would need to reproduce it to fix it. A little more info would be nice :)

**Comment by asromain** [comment]
Yes of course and thank you for your answer :). 

I have a list of pastebin's ids and to complete the text, I called getPaste(<id>) ... I had something like  

`
...
for (id of ids) {
        let text = await myPastebin.getPaste(id);
        paste.text = text;
 }
...
`

I saw on the offical doc, that we could also simply call this url https://pastebin.com/raw/<id_pastebin>

**Comment by Tox1k** [comment]
Hello!
I have issued a pull request that fixes the problem :)

**Comment by j3lte** [comment]
Thanks for the fix. Merged in 1.0.5
