### ISSUE TITLE
Post by guest with developer api key

### ISSUE THREAD

**Issue by PeterDaveHello** [j3lte/pastebin-js#5]
Hi @j3lte, 

Thanks for this awesome tool, I just wonder if this is correct,
I setup the api key, even try with username/password,
but the posts show that I'm a guest on the posts,
any suggestion?

Thanks a lot!

**Comment by PeterDaveHello** [comment]
http://pastebin.com/api#8

**Comment by j3lte** [comment]
You found it?

**Comment by PeterDaveHello** [comment]
Not sure, but you can take a look at the link above, dev key is not enough.
