### ISSUE TITLE
synchronous method support

### ISSUE THREAD

**Issue by PeterDaveHello** [j3lte/pastebin-js#6]
It'll be great to have it :smile:

**Comment by j3lte** [comment]
If you have a pull request, by all means :+1: 
Will look into it this week

**Comment by PeterDaveHello** [comment]
ooop, I am not sure when do I have time to write it ...

**Comment by j3lte** [comment]
Synchronous support added in [v0.4.0](https://github.com/j3lte/pastebin-js/releases/tag/v0.4.0), see README

**Comment by PeterDaveHello** [comment]
Oh great! Thanks @j3lte :+1:
