### ISSUE TITLE
Cannot read property of 'statusCode' of undefine 

### ISSUE THREAD

**Issue by danielps1** [j3lte/pastebin-js#8]
getting this error 

pastebin-js/lib/methods.js:79
            var status = response.statusCode;
                                 ^

TypeError: Cannot read property 'statusCode' of undefined

I was using node version 4.2.2 also tried 4.2.1, is it possible that my file was too big or something?

Edit: The Issue is that pastebin only allows 500kb files on a free account. Maybe a error could be implented here for that case.

**Comment by j3lte** [comment]
That's weird. Response should always be an object. Can you send an example code where it goes wrong? You try to send a file too big? Response should be sent in the deferred.resolve or reject. I'll check the code.

**Comment by danielps1** [comment]
Code looks like this, the logFile was bigger than 500kb in the case of the error

cfg.pastebin.createPasteFromFile(logFile, 'logs for ' + logsFor,null,2) 
                        .then(function (data) {
                            client.say(channel, '@' + user.username + ', pastebin.com/' + data);
                            console.log('Pastebin created: ' + data);
                            setTimeout(function(){
                                cfg.pastebin.deletePaste(data)
                                console.log('Pastebin deleted: ' + data)
                            }, 600000);    
                        })
                        .fail(function (err) {
                                client.say(channel, err);
                                console.log(err);
                        });

**Comment by j3lte** [comment]
Try to update pastebin-js to 0.3.4 and see what kind of error you get

**Comment by danielps1** [comment]
I can't reproduce the error now. so it looks good.

**Comment by j3lte** [comment]
Well that might look good, but not having a response usually means that there isn't a paste uploaded, I guess ;-)

**Comment by j3lte** [comment]
Closing the issue for now
