### ISSUE TITLE
Issue with newer node.js versions

### ISSUE THREAD

**Issue by Tuqiri** [j3lte/pastebin-js#9]
Using node.js version 5.6.0 seems to be an issue with sending the request to pastebin the error is as follows:

_http_outgoing.js:339
    throw new TypeError(
    ^

TypeError: Header name must be a valid HTTP Token ["Cache-Control:"]
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:339:11)
    at new ClientRequest (_http_client.js:85:14)
    at Object.exports.request (http.js:31:10)

Currently got a pull request that fixes this issue pending

**Comment by j3lte** [comment]
Fixed in [v0.3.5](https://github.com/j3lte/pastebin-js/releases/tag/v0.3.5), thanks @Tuqiri
